---
services:
  pihole:
    image: docker.io/pihole/pihole:2026.04.0
    container_name: pihole
    network_mode: host
    depends_on: [unbound]
    cap_add: [SYS_NICE]
    environment:
      TZ: America/New_York
    volumes: [./data:/etc/pihole]
    restart: unless-stopped
  unbound:
    build:
      context: ./unbound
      dockerfile: Dockerfile
    container_name: unbound
    network_mode: host
    volumes: [./unbound:/opt/unbound/etc/unbound:ro]
    restart: unless-stopped
